### ISSUE TITLE
Transfer `django-simple-history` to Django Commons

### ISSUE THREAD

**Issue by ddabble** [jazzband/django-simple-history#1391]
*This is for tracking the progress of the idea started in https://github.com/django-commons/membership/issues/40#issue-2526174875.*

To my knowledge, Jazzband has only one admin currently, and adding more has been an ongoing issue for a while now (see https://github.com/jazzband/help/issues/196). Quoting [the Django Commons FAQ](https://github.com/django-commons/membership/blob/6e0f594a89e1d0477359a3c612a64711f5d6a5eb/README.md#what-are-the-differences-between-django-commons-and-jazzband):
> Given the importance of several of these projects it's a major risk to the community at large to have a single point of failure in managing the projects.

A transfer will allow us to merge #1305 and make us better able to avoid similar problems/delays in the future, as I think it's much more likely there will be more admins available.

The only two currently active maintainers, @tim-schilling and I, are both members of Django Commons, so the transfer won't change anything in that regard (other than opening up for more maintainers from Django Commons).

[The two project leads](https://jazzband.co/projects/django-simple-history), @treyhunner and @rossmechanic, have already expressed support of this decision ([from Trey](https://github.com/django-commons/membership/issues/40#issuecomment-2351033723); [from Ross](https://github.com/jazzband/django-simple-history/issues/1391#issuecomment-2509471579)), and [so has Tim](https://github.com/django-commons/membership/issues/40#issuecomment-2350965164).

### Remaining work
- [x] Create an inbound transfer issue in [django-commons/membership](https://github.com/django-commons/membership): https://github.com/django-commons/membership/issues/131
- [x] Create an outbound transfer issue in [jazzband/help](https://github.com/jazzband/help): https://github.com/jazzband/help/issues/382
- [x] Update our `CODE_OF_CONDUCT.md` to reference [Django Commons Code of Conduct](https://github.com/django-commons/membership/blob/main/CODE_OF_CONDUCT.md): https://github.com/jazzband/django-simple-history/pull/1429
- [x] Update all references to Jazzband with Django Commons: https://github.com/jazzband/django-simple-history/pull/1429

**Comment by ddabble** [comment]
*(@-ing [all current project leads and members](https://jazzband.co/projects/django-simple-history))*
@treyhunner @rossmechanic
@tim-schilling @jeking3 @thisisazeez @LeMinaw @valberg @brylie @johanneswilm @ddabble @thesayfulla @mraza007

Taking inspiration from https://github.com/django-commons/membership/issues/34#issue-2445279361, who will be the new maintainers(/admins?) of the project? (I'm assuming that it's required of all maintainers to [join Django Commons](https://github.com/django-commons/membership/blob/main/README.md#how-to-join-as-a-contributor) first.)

To mirror what I wrote in the issue description, I guess it would be natural for at least @tim-schilling and I to continue as maintainers.

**Comment by tim-schilling** [comment]
@ddabble You're correct, @cunla and @Stormheg are the two to reach out to. The onboarding process is still being streamlined.

In regards to my role with django-simple-history, I'm good with it moving over to django-commons. I am curious who among the current releasers still wants to be a releaser and if folks are comfortable handing those keys over to @ddabble (I'm +1 on that).

**Comment by cunla** [comment]
> Also, taking inspiration from [jazzband/help#369 (comment)](https://github.com/jazzband/help/issues/369#issue-2470466800), who should be contacted for transferal of the repo? @cunla?

Hi @ddabble,
Please book some time with me to do the transfer: https://cal.com/daniel-moran/dc-meeting

**Comment by ddabble** [comment]
@cunla No, I meant which Django Commons admin should be mentioned in the issue that will be created in [jazzband/help](https://github.com/jazzband/help) - in the same fashion that you're mentioned in https://github.com/jazzband/help/issues/369#issue-2470466800 🙂 Though I guess Tim already answered that:
> when there's consensus to move it over, the scheduling will be coordinated in the django-commons/membership issue for transferring it in.

Or did I misunderstand what you meant, and that having a meeting would be useful in any case? If so, then sure 👍

**Comment by tim-schilling** [comment]
Is @rossmechanic the last person we need to talk with for this move?

**Comment by ddabble** [comment]
@tim-schilling Maybe, or perhaps the support of 1/2 project leads is enough? I suppose @jezdez could answer that - either here or once we start the move 🙂

**Comment by ddabble** [comment]
Oh great, thanks for taking the initiative! 😊

**Comment by rossmechanic** [comment]
Fine with the move. Let me know what I need to do!

**Comment by ddabble** [comment]
@rossmechanic Fantastic! Not sure you need to do anything.. 🤔 @tim-schilling Am I correct in assuming that after https://github.com/jazzband/help/issues/382 has been resolved, @jezdez can simply transfer the repo to Django Commons without any other actions being required by the people mentioned here..?

**Comment by ddabble** [comment]
Due to a lack of responses to [my comment above](https://github.com/jazzband/django-simple-history/issues/1391#issuecomment-2351583027), I'll just put @tim-schilling and I as the new maintainers of the project in https://github.com/django-commons/membership/issues/131 - but to the people I @-ed in the mentioned comment: You're very much welcome to apply for membership and a maintainer role in [django-commons](https://github.com/django-commons/membership/issues/new/choose) 😊

**Comment by tim-schilling** [comment]
@rossmechanic @treyhunner I'm going to leave both of you as owners on the PyPI project for the next month. After that, I'll remove you two unless you say differently.

I'm going to remove PyPI access from @barm @ThePumpingLemma @macro1 @kseever shortly. If there are concerns, we can always re-add. Please let us know if there are any questions or concerns.

**Comment by ddabble** [comment]
Closing, now that all the issues and PRs mentioned in the issue description have been resolved :)

**Comment by tim-schilling** [comment]
Sorry for another ping, @ThePumpingLemma and @kseever, I am going to remove you as maintainers from the ReadTheDocs project. We've added the Django Commons admin backstop, which handles the lottery/bus factor. Thank you for everything!
